name: Production build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Start Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: Build project in production
        run: npm run build:prod
      - name: Linting typescript
        run: npm run lint:ts
      - name: Linting css
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit
